"""Assembles parts/*.json into assets/questions.js after validating the combined paper."""
import json, pathlib, subprocess, sys

here = pathlib.Path(__file__).parent
parts = sorted(p for p in (here / "parts").glob("*.json") if "scenarios" in json.loads(p.read_text()))
if subprocess.call([sys.executable, str(here / "validate.py"), *sys.argv[1:], *map(str, parts)]):
    sys.exit("validation failed — not building")
scen, qs = [], []
for p in parts:
    d = json.loads(p.read_text())
    scen += d["scenarios"]
    qs += d["questions"]
exam = {"minutes": 120, "passMark": 0.72, "scenarios": scen, "questions": qs}
header = ("/* CCA-F Mock Exam #6 — real-exam-style item bank. GENERATED by build.py from parts/*.json;\n"
          "   edit the parts and rebuild. Rules: parts/SPEC.md. Checker: validate.py. */\n")
(here / "assets" / "questions.js").write_text(header + "window.EXAM = " + json.dumps(exam, ensure_ascii=False, indent=1) + ";\n")
print(f"built {len(qs)} items in {len(scen)} scenarios")
